from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
from main.models import *

def validate_unb_email(value):
    if not value.endswith('@aluno.unb.br'):
        raise ValidationError('Por favor, utilize um email da UNB v치lido.')

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(validators=[validate_unb_email])

    class Meta:
        model = CustomUser
        fields = ('email',)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = user.email  # Define o username como o email
        if commit:
            user.save()
        return user

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'username', 'followed_forums', 'liked_questions', 'created_questions', 'created_answers', 'is_active', 'is_staff')
        field_classes = {
            'created_questions': forms.ModelMultipleChoiceField,
            'created_answers': forms.ModelMultipleChoiceField,
        }
    created_questions = forms.ModelMultipleChoiceField(queryset=Question.objects.all(), required=False)
    created_answers = forms.ModelMultipleChoiceField(queryset=Answer.objects.all(), required=False)

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'photo']

    def clean_username(self):
        username = self.cleaned_data['username']
        if CustomUser.objects.filter(username=username).exclude(id=self.instance.id).exists():
            raise forms.ValidationError("Este nome de usu치rio j치 est치 em uso.")
        return username